/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Web Practice Tech API
 * Web Practice Tech API
 * OpenAPI spec version: 0.0.1
 */
export interface PostsListResponseBodyInner {
  completed: string;
  id: number;
  title: string;
  userId: number;
}

export type PostsListResponseBody = PostsListResponseBodyInner[];

