/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Web Practice Tech API
 * Web Practice Tech API
 * OpenAPI spec version: 0.0.1
 */
export interface UserCompany {
  bs?: string;
  catchPhrase?: string;
  name?: string;
}

export interface UserAddressGeo {
  lat?: string;
  lon?: string;
}

export interface UserAddress {
  city?: string;
  geo?: UserAddressGeo;
  street?: string;
  suite?: string;
  zipcode?: string;
}

export interface PostDetailCommentListResponseBodyInner {
  body: string;
  email: string;
  id: number;
  name: string;
  postId: number;
}

export type UserDetailCommentListResponseBody = PostDetailCommentListResponseBodyInner[];

export interface User {
  address: UserAddress;
  company?: UserCompany;
  email: string;
  id: number;
  name: string;
  phone?: string;
  username: string;
  website?: string;
}

export type UserResponseBody = User;

export type UserListResponseBody = User[];

export type PostDetailCommentListResponseBody = PostDetailCommentListResponseBodyInner[];

export interface Post {
  completed: string;
  id: number;
  title: string;
  userId: number;
}

export type PostResponseBody = Post;

export type PostsListResponseBody = Post[];

