/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Web Practice Tech API
 * Web Practice Tech API
 * OpenAPI spec version: 0.0.1
 */
import { faker } from '@faker-js/faker';
import { HttpResponse, delay, http } from 'msw';

export const getGetCityListMock = () => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.word.sample(),
    name: faker.word.sample(),
  })),
  status: faker.word.sample(),
});

export const getWeblandMock = () => [
  http.get('*/webland/api/CitySearch', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(getGetCityListMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }),
];
